### ISSUE TITLE
Calf Multi Spread - Intensity controls automation scale is broken

### ISSUE THREAD

**Issue by unfa** [calf-studio-gear/calf#153] opened 2017-11-17 19:33 UTC
I just discovered this new plugin in calf-plugins-git - it can make sore really interesting sounds!

I've noticed that the Intensity knobs are exposed to the host in such a way that in Ardour 5 the automation is very difficultm because 98% of the fader space is jsut for positive values, and the last 2% is left for the negative values.

I'd expect the neutral 0dB value to be in the middle, but it's not the case:

![image](https://user-images.githubusercontent.com/491704/32965367-8cbad0e8-cbd6-11e7-8e00-33ba42b045df.png)

**Comment by boomshop** [comment] 2017-11-21 00:19
Duplicate of #2

**Closed by boomshop** 2017-11-21 00:19 UTC
