### ISSUE TITLE
LV2 Calf Equalizer Input/Output Gain not reflected correctly in host automation

### ISSUE THREAD

**Issue by yubatake** [calf-studio-gear/calf#96] opened 2016-10-02 04:53 UTC
Input/Output Gain controls seemingly do not designate proper units/properties for control port parameters, leading to a mismatch of values in the host when automating the plugin. For example, when automating Input Gain in Qtractor:

Qtractor automation nodes run from 0-64, not reflecting the dB values in Calf
Qtractor automation node of 5 = 14dB in Calf
Qtractor automation node of 0.5 = -4.5dB in Calf

This occurs with all Equalizer variants (5/8/12/30 Band).

Using latest stable release: calf-0.0.60pre5.

**Comment by boomshop** [comment] 2017-11-21 00:20
Duplicate of #2

**Closed by boomshop** 2017-11-21 00:20 UTC
Labels: enhancement
