### ISSUE TITLE
calf-plugins 0.90.2 crashing on some architectures e.g. i386

### ISSUE THREAD

**Issue by RossGammon** [calf-studio-gear/calf#232] opened 2019-06-23 08:34 UTC
I have packaged calf-plugins 0.90.2 for Debian experimental (due to the release freeze) and tried to syncronise this package in Ubuntu. But the automatic package tests are failing on 32 bit architectures, and therefore the package does not migrate into the release pocket. The test command generates a segmentation fault.

The automatic tests can be replicated on a 64 bit Ubuntu machine by installing the 32 bit foreign architecture package, and simply running:
$ calfjackhost --version
calf 0.90.2
Segmentation fault (core dumped)

Here is a part of the stacktrace:
#0  0x565bbd7d in calf_plugins::host_session::~host_session (this=0xfff5b5d8, __in_chrg=<optimized out>) at host_session.cpp:649
No locals.
#1  0x565b6532 in main (argc=<optimized out>, argv=<optimized out>) at /usr/include/i386-linux-gnu/bits/stdio2.h:107
        sess = {<calf_plugins::main_window_owner_iface> = {_vptr.main_window_owner_iface = 0x56642e10 <vtable for calf_plugins::host_session+8>}, <calf_plugins::session_client_iface> = {_vptr.session_client_iface = 0x56642e54 <vtable for calf_plugins::host_session+76>}, static instance = 0x0, client_name = "Calf Studio Gear", input_name = "", output_name = "", midi_name = "", load_name = "", only_load_if_exists = false, plugin_names = std::vector of length 0, capacity 0, presets = std::map with 0 elements, session_manager = 0x0, save_file_on_next_idle_call = false, quit_on_next_idle_call = 0, handle_event_on_next_idle_call = 0x0, current_filename = "", jack_session_id = "", calfjackhost_cmd = "calfjackhost", client = {plugins = std::vector of length 0, capacity 0, mutex = {pm = {__data = {__lock = 0, __count = 0, __owner = 0, __kind = 1, __nusers = 0, {__elision_data = {__espins = 0, __eelision = 0}, __list = {__next = 0x0}}}, __size = '\000' <repeats 12 times>, "\001\000\000\000\000\000\000\000\000\000\000", __align = 0}}, automation_port = 0x0, client = 0x0, input_nr = 1, output_nr = 1, midi_nr = 1, name = "", input_name = "input_%d", output_name = "output_%d", midi_name = "midi_%d", sample_rate = 0}, autoconnect_midi = "", autoconnect_midi_index = -1, chains = std::set with 0 elements, plugins = std::vector of length 0, capacity 0, main_win = 0x8, instances = std::set with 0 elements, has_gui = true, has_trayicon = true, gui_win = 0x0, session_env = 0x56d7f040}

Further attachments about the environment and the crash can be found on the Ubuntu bug:
https://bugs.launchpad.net/ubuntu/+source/calf/+bug/1833840

Regards,
Ross

**Comment by boomshop** [comment] 2019-06-23 09:01
Hey Ross,

thanks for the report! Since I don't have this kind of build environment - could you please help out by trying to bisect the broken commit?

Best
Markus

**Comment by RossGammon** [comment] 2019-06-23 09:39
I will have to set up a 32bit chroot on my machine to do that, and I am quite busy at the moment so it may take some time.
As the tests passed fine on the previous release in Debian and Ubuntu, I can confirm the bad commit is somewhere between the 0.90.1 release and 0.90.2.

**Comment by trebmuh** [comment] 2019-06-23 12:20
Just to let you know, I've got a home (pbuilder) made package for 0.90.2, and it calf-fluidsynth works on a 32 bits system here.

That said, I've got that too:
```
$ calfjackhost --version
calf 0.90.2
Segmentation fault (core dumped)
```

On a 64 bits version, I've got the same:
```
$ calfjackhost --version
calf 0.90.2
Segmentation fault (core dumped)
```

**Comment by boomshop** [comment] 2019-06-23 19:09
Yes, I merged a couple of commits from other forks in the meantime and would like to know which is the bad apple in the basket. Thanks a bunch in advance!

**Comment by trebmuh** [comment] 2019-06-23 19:54
@boomshop : yw

@RossGammon can you update the issue title accordingly?

**Comment by RossGammon** [comment] 2019-06-28 21:21
I updated the title. The list of architectures and the test status is:
autopkgtest for calf/0.90.2-1: amd64: Pass, arm64: Regression ♻ , armhf: Regression ♻ , i386: Regression ♻ , ppc64el: Pass, s390x: Regression

I have confirmed the crash at the current git HEAD, and no crash at the 0.90.1 tag in a i386 chroot (Debian sid). Git bisect is reporting 2 more steps to find the bad commit. Will report soon.

**Comment by RossGammon** [comment] 2019-06-28 21:33
calf# git bisect good
199ead096dc43f00bc31cbb1e978896a2f006101 is the first bad commit
commit 199ead096dc43f00bc31cbb1e978896a2f006101
Author: jimzrt <james.tophoven@gmail.com>
Date:   Mon Feb 11 12:10:33 2019 +0100

    fix headless mode

:100644 100644 c3a05d8f5e0defce7e92984966bf0b85f2bcbed8 f16a1f7e7e929943ebca7476ccf207cbc58a6789 M	.gitignore
:040000 040000 58e1b6c33e7d195f3728123b559fa3322a0d7cc5 790eda7e606fbf126d446696393e7e84703e7dcb M	src

**Comment by boomshop** [comment] 2019-06-29 09:36
Thanks a lot for the findings, I informed James about the issue.

**Comment by boomshop** [comment] 2019-07-12 20:36
Could you please test the fix?

**Comment by eeickmeyer** [comment] 2019-07-13 02:50
@boomshop, FYI, @RossGammon is on vacation with limited internet access for the next few weeks. I'll see what I can do to test it.

**Comment by eeickmeyer** [comment] 2019-07-13 04:03
Applied the patch via quilt, built and installed foreign architecture version. Test was successful, no segfault. Confirmed fixed, feel free to close.

@RossGammon, I'm going to throw this in the backports, but it should clear to get into eoan via Debian with the patch.

**Comment by boomshop** [comment] 2019-07-13 05:35
Thanks for information and testing! I'll prepare 0.90.3 tomorrow.

**Comment by boomshop** [comment] 2019-07-16 16:32
Sorry for the delay. I just pushed tag 0.90.3 including James' fix.

**Closed by boomshop** 2019-07-16 16:32 UTC
