### ISSUE TITLE
LV2 build broken

### ISSUE THREAD

**Issue by nefthy** [calf-studio-gear/calf#325] opened 2023-04-04 20:50 UTC
The lv2 plugins do get installed properly since PR #288. The $PREFIX/lib/lv2/calf.lv2/calf.so simlink points to $PREFIX/lib/calf/calf.so which does not exist and the calflv2gui.so is missing from the lv2 directory.

**Comment by falkTX** [comment] 2023-04-04 21:11
this is a duplicate of #294

**Closed** 2023-04-04 22:07 UTC
