### ISSUE TITLE
Ardour 5.8 crashes with Calf version 0.0.60-4 

### ISSUE THREAD

**Issue by tone6120** [calf-studio-gear/calf#130] opened 2017-05-06 13:55 UTC
Since upgrading to Ubuntu Studio 17.04 Ardour crashes on start up. Removing the plugins allows Ardour to start. As the plugins are very useful this is not an option. 

dmesg output:

[22917.753918] ardour-5.8.0[21147]: segfault at 1bb8cde0 ip 00007fe5d8636284 sp 00007ffe2dde0a70 error 6 in calf.so[7fe5d8583000+108000]
[24820.038202] ardour-5.8.0[24137]: segfault at 166d8720 ip 00007ff9ea7ccc04 sp 00007ffe45d10630 error 6 in calf.so[7ff9ea712000+108000]

**Comment by GertrudH** [comment] 2017-05-06 14:10
Does the git version run smoothly?

**Comment by boomshop** [comment] 2017-05-06 14:12
Does the git version run smoothly?

**Comment by tone6120** [comment] 2017-05-06 21:47
I don't know. Do i have to build from source to get these versions? That's not something I've done before.

**Comment by fathomstory** [comment] 2017-05-16 00:04
I run AV Linux on a 64 bit system and the Calf 1) Has no GUI when you double click them (such as the analyzer) on the mixer and/or 2) if you drag a plugin to the mixer, such as the Calf Compressor all of Ardour crashes. The Ardour channel was not exactly encouraging. I could run a debugger program while running Ardour and submit...if that may provide anything useful. However, other plugins seem to work okay. When I first installed AV Linux, the Calf plugins function well. The repositories I use are both the Kstudio and Github repository. I have the option of one or the other, both will crash Ardour. I tried Calf plugins on Audacity, same issue, it crashes.

**Comment by falkTX** [comment] 2017-05-16 00:05
Since you're using kxstudio repos, install calf-plugins-git and see if the situation improves.
The last 'stable' release is not really stable now...

**Comment by fathomstory** [comment] 2017-05-16 00:07
@falkTX Yes, sorry for not being more clear. I have installed calf-plugins-git, same result.

**Comment by boomshop** [comment] 2017-05-16 16:42
Strange. Unfortunately I'm not able to reproduce the bug using Ardour 5.8.0 from KX and Calf built from latest git on Debian unstable - everything works flawlessly as expected, no crashes. Can anyone else reproduce this? And yes - some backtrace could probably be helpful in this case.

**Comment by fathomstory** [comment] 2017-05-16 17:51
Last night I uninstalled all Calf plugins and shut my machine down. Today I got the messages here and was going to run the debugger so I booted my machine and installed the git version of Calf Studio gear. Lo and behold, it works now. There is something about a complete uninstall and reboot that makes the plugins operational. Simply switching repos does not seem to be enough. This may go back to boomshop's original comment.

**Comment by boomshop** [comment] 2017-05-16 17:56
> I don't know. Do i have to build from source to get these versions? That's not something I've done before.

Oops sorry for not getting back to you. The most easy way is to add FalkTX's famous KXStudio repositories as described here:

http://kxstudio.linuxaudio.org/Repositories

and then to install calf-plugins-git package to avoid building it on your own.

**Comment by tone6120** [comment] 2017-05-24 21:15
My turn for apologies now.

I installed version 0.0.60-1 using the kx repos and ardour no longer crashed. 17.04 also gave problems with my external monitor. The system just freezes. So i have uninstalled 17.04 and reverted to 16.04 lts of ubuntu studio.

**Comment by boomshop** [comment] 2017-05-24 21:57
Thanks for reporting back! Time to close this issue.

**Closed by boomshop** 2017-05-24 21:57 UTC

**Comment by tone6120** [comment] 2017-05-25 06:43
There's still an issue but who knows what the cause is: ardour, 0.0.60-4, or something further down the stack. I've just avoided it for now. I'll open a new issue if it happens again. Thanks
